name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Установка pre-commit
        run: |
          python -m pip install pre-commit

      - name: Запуск pre-commit
        run: |
          pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Установка зависимостей Poetry
        run: |
          python -m pip install poetry

      - name: Проверка синтаксиса
        run: |
          python -m py_compile src/ventilation.py

      - name: Запуск mypy
        run: |
          python -m mypy ventilation.py

      - name: Запуск flake8
        run: |
          python -m flake8 ventilation.py

